name: Build and Push Docker Image for Dev Portfolio

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Set up environment variables
      run: |
        echo "PUBLIC_BACKEND_URL=${{ secrets.PUBLIC_BACKEND_URL }}" >> $GITHUB_ENV
        echo "PUBLIC_IMGHOSTING_URL=${{ secrets.PUBLIC_IMGHOSTING_URL }}" >> $GITHUB_ENV
        echo "PUBLIC_DOMAIN_URL=${{ secrets.PUBLIC_DOMAIN_URL }}" >> $GITHUB_ENV
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
      
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dev-portfolio:latest .
      
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dev-portfolio:latest
